[package]
name = "remotelink"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
rand = "0.8"
argon2 = "0.5"
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
hostname = "0.3"
machine-uid = "0.3"
sysinfo = "0.30"
anyhow = "1.0"
hex = "0.4"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
opt-level = "z"
strip = true
